/**
 * Generates src/generated/embedded.ts: the in-page scripts and the PDF fonts as string constants.
 * Bundlers (esbuild for Docker, Next/Turbopack for Vercel) can't follow runtime file reads, so
 * these assets are compiled in. inpage/*.js stays the source of truth; a unit test fails if the
 * generated file is stale.
 *
 *   pnpm --filter @teardown/scanner gen
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = fileURLToPath(new URL('..', import.meta.url));

export function buildEmbedded(): string {
  const inpage = (name: string) => readFileSync(join(root, 'inpage', `${name}.js`), 'utf8').trim();
  const face = (pkg: string, family: string, file: string, weight: number) => {
    const dir = dirname(require.resolve(`${pkg}/package.json`));
    const b64 = readFileSync(join(dir, 'files', file)).toString('base64');
    return `@font-face{font-family:'${family}';font-weight:${weight};font-style:normal;src:url(data:font/woff2;base64,${b64}) format('woff2');}`;
  };
  const fonts = [
    face('@fontsource/big-shoulders-display', 'Big Shoulders Display', 'big-shoulders-display-latin-700-normal.woff2', 700),
    face('@fontsource/big-shoulders-display', 'Big Shoulders Display', 'big-shoulders-display-latin-800-normal.woff2', 800),
    face('@fontsource/public-sans', 'Public Sans', 'public-sans-latin-400-normal.woff2', 400),
    face('@fontsource/public-sans', 'Public Sans', 'public-sans-latin-600-normal.woff2', 600),
    face('@fontsource/martian-mono', 'Martian Mono', 'martian-mono-latin-400-normal.woff2', 400),
  ].join('\n');
  return [
    '// GENERATED by scripts/gen-embedded.ts. Do not edit; edit inpage/*.js and re-run `pnpm --filter @teardown/scanner gen`.',
    `export const INPAGE_COLLECT = ${JSON.stringify(inpage('collect'))};`,
    `export const INPAGE_MOBILE = ${JSON.stringify(inpage('mobile'))};`,
    `export const PDF_FONTS_CSS = ${JSON.stringify(fonts)};`,
    '',
  ].join('\n');
}

export const EMBEDDED_PATH = join(root, 'src', 'generated', 'embedded.ts');

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  mkdirSync(dirname(EMBEDDED_PATH), { recursive: true });
  writeFileSync(EMBEDDED_PATH, buildEmbedded());
  console.log(`wrote ${EMBEDDED_PATH}`);
}
